using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyTrading.Infrastructure.Migrations;

[DbContext(typeof(EnergyTradingDbContext))]
[Migration("202608180005_AddRawTransparencyJobs")]
public partial class AddRawTransparencyJobs : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DO $$
            DECLARE table_name text;
            BEGIN
              FOREACH table_name IN ARRAY ARRAY[
                'final_generation_plan_snapshots','new_installed_capacity_snapshots','planned_power_outage_snapshots',
                'unplanned_power_outage_snapshots','sgp_price_snapshots','available_installed_capacity_snapshots',
                'unlicensed_generation_snapshots','real_time_generation_snapshots','order_summary_up_snapshots',
                'order_summary_down_snapshots','clearing_quantity_snapshots','idm_weighted_average_price_snapshots',
                'idm_matching_quantity_snapshots','withdrawal_quantity_snapshots','idm_contract_summary_snapshots'
              ] LOOP
                EXECUTE format('CREATE TABLE %I (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, payload jsonb NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL)', table_name);
                EXECUTE format('CREATE UNIQUE INDEX %I ON %I (date,time_of_period_id)', 'ix_' || table_name || '_date_time_of_period_id', table_name);
              END LOOP;
            END $$;

            INSERT INTO integration_jobs (id,name,code,description,cron_expression,time_zone,queue_name,is_active,created_date) VALUES
              (12,'Kesinleştirilmiş Uzlaştırma Dönemi Üretim Planı','TRANSPARENCY_FINAL_GENERATION_PLAN','KUDÜP/SBFGP verilerini getirir.','30 16 * * *','Europe/Istanbul','transparency',true,now()),
              (13,'Yeni Kurulu Güç','TRANSPARENCY_NEW_INSTALLED_CAPACITY','Yeni kurulu güç verilerini getirir.','0 6 * * *','Europe/Istanbul','transparency',true,now()),
              (14,'Planlı Elektrik Kesintileri','TRANSPARENCY_PLANNED_POWER_OUTAGE','Planlı kesinti verilerini getirir.','0 * * * *','Europe/Istanbul','transparency',true,now()),
              (15,'Plansız Elektrik Kesintileri','TRANSPARENCY_UNPLANNED_POWER_OUTAGE','Plansız kesinti verilerini getirir.','30 * * * *','Europe/Istanbul','transparency',true,now()),
              (16,'SGP Fiyatı','TRANSPARENCY_SGP_PRICE','Doğal gaz SGP fiyatlarını getirir; kontrat doğrulaması bekleniyor.','10 * * * *','Europe/Istanbul','transparency',false,now()),
              (17,'Emre Amade Kapasite','TRANSPARENCY_AVAILABLE_INSTALLED_CAPACITY','EAK/AİC verilerini getirir.','25 * * * *','Europe/Istanbul','transparency',true,now()),
              (18,'Lisanssız Üretim Miktarı','TRANSPARENCY_UNLICENSED_GENERATION','Lisanssız üretim miktarlarını getirir.','0 3 * * *','Europe/Istanbul','transparency',true,now()),
              (19,'Gerçek Zamanlı Üretim','TRANSPARENCY_REALTIME_GENERATION','Gerçek zamanlı üretim verilerini getirir.','15 3 * * *','Europe/Istanbul','transparency',true,now()),
              (20,'YAL Talimat Özeti','TRANSPARENCY_ORDER_SUMMARY_UP','Yük alma talimat miktarlarını getirir.','35 * * * *','Europe/Istanbul','transparency',true,now()),
              (21,'YAT Talimat Özeti','TRANSPARENCY_ORDER_SUMMARY_DOWN','Yük atma talimat miktarlarını getirir.','40 * * * *','Europe/Istanbul','transparency',true,now()),
              (22,'GÖP Eşleşme Miktarı','TRANSPARENCY_CLEARING_QUANTITY','GÖP eşleşme miktarlarını getirir.','10 15 * * *','Europe/Istanbul','transparency',true,now()),
              (23,'GİP Ağırlıklı Ortalama Fiyat','TRANSPARENCY_IDM_WEIGHTED_AVERAGE_PRICE','GİP ağırlıklı ortalama fiyatlarını getirir.','45 * * * *','Europe/Istanbul','transparency',true,now()),
              (24,'GİP Eşleşme Miktarı','TRANSPARENCY_IDM_MATCHING_QUANTITY','GİP eşleşme miktarlarını getirir.','50 * * * *','Europe/Istanbul','transparency',true,now()),
              (25,'Uzlaştırmaya Esas Çekiş Miktarı','TRANSPARENCY_UECM','UEÇM verilerini getirir.','30 3 * * *','Europe/Istanbul','transparency',true,now()),
              (26,'GİP Kontrat Özeti','TRANSPARENCY_IDM_CONTRACT_SUMMARY','GİP kontrat özetlerini getirir; kontrat doğrulaması bekleniyor.','55 * * * *','Europe/Istanbul','transparency',false,now())
            ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, cron_expression=EXCLUDED.cron_expression, is_active=EXCLUDED.is_active;
            SELECT setval(pg_get_serial_sequence('integration_jobs','id'), (SELECT MAX(id) FROM integration_jobs));
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DELETE FROM integration_jobs WHERE id BETWEEN 12 AND 26;
            DO $$
            DECLARE table_name text;
            BEGIN
              FOREACH table_name IN ARRAY ARRAY[
                'final_generation_plan_snapshots','new_installed_capacity_snapshots','planned_power_outage_snapshots',
                'unplanned_power_outage_snapshots','sgp_price_snapshots','available_installed_capacity_snapshots',
                'unlicensed_generation_snapshots','real_time_generation_snapshots','order_summary_up_snapshots',
                'order_summary_down_snapshots','clearing_quantity_snapshots','idm_weighted_average_price_snapshots',
                'idm_matching_quantity_snapshots','withdrawal_quantity_snapshots','idm_contract_summary_snapshots'
              ] LOOP EXECUTE format('DROP TABLE %I', table_name); END LOOP;
            END $$;
            """);
    }
}
