using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyTrading.Infrastructure.Migrations;

[DbContext(typeof(EnergyTradingDbContext))]
[Migration("202608180007_ReplaceRawSnapshotsWithTypedTables")]
public partial class ReplaceRawSnapshotsWithTypedTables : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql(
        """
        DROP TABLE final_generation_plan_snapshots, new_installed_capacity_snapshots,
          planned_power_outage_snapshots, unplanned_power_outage_snapshots,
          available_installed_capacity_snapshots, unlicensed_generation_snapshots,
          real_time_generation_snapshots, order_summary_up_snapshots,
          order_summary_down_snapshots, clearing_quantity_snapshots,
          idm_weighted_average_price_snapshots, idm_matching_quantity_snapshots,
          withdrawal_quantity_snapshots;

        CREATE TABLE final_generation_plan_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          river numeric(18,6) NOT NULL, dam numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL,
          other numeric(18,6) NOT NULL, natural_gas numeric(18,6) NOT NULL, fuel_oil numeric(18,6) NOT NULL,
          solar numeric(18,6) NOT NULL, imported_coal numeric(18,6) NOT NULL, geothermal numeric(18,6) NOT NULL,
          lignite numeric(18,6) NOT NULL, naphtha numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL,
          hard_coal numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_final_generation_plan_snapshots_date_time_of_period_id ON final_generation_plan_snapshots(date,time_of_period_id);

        CREATE TABLE available_installed_capacity_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          river numeric(18,6) NOT NULL, dam numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL,
          other numeric(18,6) NOT NULL, natural_gas numeric(18,6) NOT NULL, fuel_oil numeric(18,6) NOT NULL,
          solar numeric(18,6) NOT NULL, imported_coal numeric(18,6) NOT NULL, geothermal numeric(18,6) NOT NULL,
          lignite numeric(18,6) NOT NULL, naphtha numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL,
          hard_coal numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_available_installed_capacity_snapshots_date_time_of_period_id ON available_installed_capacity_snapshots(date,time_of_period_id);

        CREATE TABLE new_installed_capacity_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          external_key varchar(300) NOT NULL, renewable_energy_type text NOT NULL,
          licensed_capacity numeric(18,6) NOT NULL, unlicensed_capacity numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL,
          created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_new_installed_capacity_snapshots_identity ON new_installed_capacity_snapshots(date,time_of_period_id,external_key);

        CREATE TABLE planned_power_outage_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          external_key varchar(300) NOT NULL, outage_id bigint NOT NULL, distribution_company_name text NOT NULL,
          province text NOT NULL, district text NOT NULL, affected_neighbourhoods text NOT NULL, affected_subscribers bigint NOT NULL,
          reason text NOT NULL, start_time timestamptz NULL, end_time timestamptz NULL, hourly_load_average numeric(18,6) NOT NULL,
          created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_planned_power_outage_snapshots_identity ON planned_power_outage_snapshots(date,time_of_period_id,external_key);
        CREATE TABLE unplanned_power_outage_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          external_key varchar(300) NOT NULL, outage_id bigint NOT NULL, distribution_company_name text NOT NULL,
          province text NOT NULL, district text NOT NULL, affected_neighbourhoods text NOT NULL, affected_subscribers bigint NOT NULL,
          reason text NOT NULL, start_time timestamptz NULL, end_time timestamptz NULL, hourly_load_average numeric(18,6) NOT NULL,
          created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_unplanned_power_outage_snapshots_identity ON unplanned_power_outage_snapshots(date,time_of_period_id,external_key);

        CREATE TABLE unlicensed_generation_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          biogas numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL, other numeric(18,6) NOT NULL,
          solar numeric(18,6) NOT NULL, channel_type numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL,
          created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_unlicensed_generation_snapshots_date_time_of_period_id ON unlicensed_generation_snapshots(date,time_of_period_id);

        CREATE TABLE real_time_generation_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          asphaltite_coal numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL, black_coal numeric(18,6) NOT NULL,
          dammed_hydro numeric(18,6) NOT NULL, fueloil numeric(18,6) NOT NULL, geothermal numeric(18,6) NOT NULL,
          import_coal numeric(18,6) NOT NULL, import_export numeric(18,6) NOT NULL, lignite numeric(18,6) NOT NULL,
          lng numeric(18,6) NOT NULL, naphta numeric(18,6) NOT NULL, natural_gas numeric(18,6) NOT NULL,
          river numeric(18,6) NOT NULL, sun numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL,
          wasteheat numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_real_time_generation_snapshots_date_time_of_period_id ON real_time_generation_snapshots(date,time_of_period_id);

        CREATE TABLE order_summary_up_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          net numeric(18,6) NOT NULL, up_regulation_delivered numeric(18,6) NOT NULL, up_regulation_one_coded numeric(18,6) NOT NULL,
          up_regulation_two_coded numeric(18,6) NOT NULL, up_regulation_zero_coded numeric(18,6) NOT NULL,
          created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_order_summary_up_snapshots_date_time_of_period_id ON order_summary_up_snapshots(date,time_of_period_id);
        CREATE TABLE order_summary_down_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          net numeric(18,6) NOT NULL, down_regulation_delivered numeric(18,6) NOT NULL, down_regulation_one_coded numeric(18,6) NOT NULL,
          down_regulation_two_coded numeric(18,6) NOT NULL, down_regulation_zero_coded numeric(18,6) NOT NULL,
          created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_order_summary_down_snapshots_date_time_of_period_id ON order_summary_down_snapshots(date,time_of_period_id);

        CREATE TABLE clearing_quantity_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          matched_bids numeric(18,6) NOT NULL, matched_offers numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_clearing_quantity_snapshots_date_time_of_period_id ON clearing_quantity_snapshots(date,time_of_period_id);
        CREATE TABLE idm_weighted_average_price_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          weighted_average_price numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_idm_weighted_average_price_snapshots_date_time_of_period_id ON idm_weighted_average_price_snapshots(date,time_of_period_id);
        CREATE TABLE idm_matching_quantity_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          external_key varchar(300) NOT NULL, clearing_quantity_ask numeric(18,6) NOT NULL, clearing_quantity_bid numeric(18,6) NOT NULL,
          contract_name text NOT NULL, contract_type text NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_idm_matching_quantity_snapshots_identity ON idm_matching_quantity_snapshots(date,time_of_period_id,external_key);
        CREATE TABLE withdrawal_quantity_snapshots (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL,
          period timestamptz NOT NULL, swv numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL);
        CREATE UNIQUE INDEX ix_withdrawal_quantity_snapshots_date_time_of_period_id ON withdrawal_quantity_snapshots(date,time_of_period_id);
        """);

    protected override void Down(MigrationBuilder migrationBuilder) => migrationBuilder.Sql(
        """
        DROP TABLE final_generation_plan_snapshots, new_installed_capacity_snapshots,
          planned_power_outage_snapshots, unplanned_power_outage_snapshots, available_installed_capacity_snapshots,
          unlicensed_generation_snapshots, real_time_generation_snapshots, order_summary_up_snapshots,
          order_summary_down_snapshots, clearing_quantity_snapshots, idm_weighted_average_price_snapshots,
          idm_matching_quantity_snapshots, withdrawal_quantity_snapshots;
        DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY[
          'final_generation_plan_snapshots','new_installed_capacity_snapshots','planned_power_outage_snapshots',
          'unplanned_power_outage_snapshots','available_installed_capacity_snapshots','unlicensed_generation_snapshots',
          'real_time_generation_snapshots','order_summary_up_snapshots','order_summary_down_snapshots',
          'clearing_quantity_snapshots','idm_weighted_average_price_snapshots','idm_matching_quantity_snapshots','withdrawal_quantity_snapshots'
        ] LOOP EXECUTE format('CREATE TABLE %I (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, payload jsonb NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL)',t); EXECUTE format('CREATE UNIQUE INDEX %I ON %I(date,time_of_period_id)','ix_'||t||'_date_time_of_period_id',t); END LOOP; END $$;
        """);
}
