using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyTrading.Infrastructure.Migrations;

[DbContext(typeof(EnergyTradingDbContext))]
[Migration("202608200003_TypeIdmContractSummaries")]
public partial class TypeIdmContractSummaries : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE idm_contract_summaries_typed (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date date NOT NULL,
              time_of_period_id integer NOT NULL,
              external_key varchar(300) NOT NULL,
              contract_name text NULL,
              contract_type_description text NULL,
              weighted_average_price numeric(18,6) NULL,
              matching_quantity numeric(18,6) NULL,
              trading_volume numeric(18,6) NULL,
              maximum_bid_price numeric(18,6) NULL,
              maximum_matching_price numeric(18,6) NULL,
              maximum_ask_price numeric(18,6) NULL,
              minimum_bid_price numeric(18,6) NULL,
              minimum_matching_price numeric(18,6) NULL,
              minimum_ask_price numeric(18,6) NULL,
              bid_quantity numeric(18,6) NULL,
              ask_quantity numeric(18,6) NULL,
              created_date timestamptz NOT NULL,
              updated_date timestamptz NULL,
              CONSTRAINT ck_idm_contract_summaries_time_of_period_id
                CHECK (time_of_period_id BETWEEN 1 AND 24),
              CONSTRAINT uq_idm_contract_summaries_identity
                UNIQUE (date, time_of_period_id, external_key)
            );

            INSERT INTO idm_contract_summaries_typed (
              date, time_of_period_id, external_key,
              contract_name, contract_type_description,
              weighted_average_price, matching_quantity, trading_volume,
              maximum_bid_price, maximum_matching_price, maximum_ask_price,
              minimum_bid_price, minimum_matching_price, minimum_ask_price,
              bid_quantity, ask_quantity, created_date, updated_date)
            SELECT
              source.date,
              source.time_of_period_id,
              left(coalesce(item->>'kontratAdi', '') || '|' || coalesce(item->>'kontratTurAciklama', ''), 300),
              item->>'kontratAdi',
              item->>'kontratTurAciklama',
              nullif(item->>'agirlikliOrtalama', '')::numeric,
              nullif(item->>'eslesmeMiktar', '')::numeric,
              nullif(item->>'islemHacmi', '')::numeric,
              nullif(item->>'maxAlisFiyat', '')::numeric,
              nullif(item->>'maxEslesmeFiyat', '')::numeric,
              nullif(item->>'maxSatisFiyat', '')::numeric,
              nullif(item->>'minAlisFiyat', '')::numeric,
              nullif(item->>'minEslesmeFiyat', '')::numeric,
              nullif(item->>'minSatisFiyat', '')::numeric,
              nullif(item->>'teklifAlisMiktar', '')::numeric,
              nullif(item->>'teklifSatisMiktar', '')::numeric,
              source.created_date,
              source.updated_date
            FROM idm_contract_summaries source
            CROSS JOIN LATERAL jsonb_array_elements(
              coalesce(source.payload->'items', '[]'::jsonb)) item
            ON CONFLICT (date, time_of_period_id, external_key) DO NOTHING;

            DROP TABLE idm_contract_summaries;
            ALTER TABLE idm_contract_summaries_typed RENAME TO idm_contract_summaries;
            ALTER INDEX uq_idm_contract_summaries_identity
              RENAME TO ix_idm_contract_summaries_date_time_of_period_id_external_key;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE idm_contract_summaries_raw (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date date NOT NULL,
              time_of_period_id integer NOT NULL,
              payload jsonb NOT NULL,
              created_date timestamptz NOT NULL,
              updated_date timestamptz NULL,
              CONSTRAINT uq_idm_contract_summaries_raw_period
                UNIQUE (date, time_of_period_id)
            );

            INSERT INTO idm_contract_summaries_raw (
              date, time_of_period_id, payload, created_date, updated_date)
            SELECT
              date,
              time_of_period_id,
              jsonb_build_object('items', jsonb_agg(jsonb_build_object(
                'agirlikliOrtalama', weighted_average_price,
                'eslesmeMiktar', matching_quantity,
                'islemHacmi', trading_volume,
                'kontratAdi', contract_name,
                'kontratTurAciklama', contract_type_description,
                'maxAlisFiyat', maximum_bid_price,
                'maxEslesmeFiyat', maximum_matching_price,
                'maxSatisFiyat', maximum_ask_price,
                'minAlisFiyat', minimum_bid_price,
                'minEslesmeFiyat', minimum_matching_price,
                'minSatisFiyat', minimum_ask_price,
                'teklifAlisMiktar', bid_quantity,
                'teklifSatisMiktar', ask_quantity))),
              min(created_date),
              max(updated_date)
            FROM idm_contract_summaries
            GROUP BY date, time_of_period_id;

            DROP TABLE idm_contract_summaries;
            ALTER TABLE idm_contract_summaries_raw RENAME TO idm_contract_summaries;
            ALTER TABLE idm_contract_summaries
              RENAME CONSTRAINT uq_idm_contract_summaries_raw_period
              TO uq_idm_contract_summaries_period;
            """);
    }
}
