using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyTrading.Infrastructure.Migrations;

[DbContext(typeof(EnergyTradingDbContext))]
[Migration("202608180004_AddTransparencyDataJobs")]
public partial class AddTransparencyDataJobs : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE load_estimation_plans (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, load_estimation numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_load_estimation_plans_period UNIQUE(date,time_of_period_id));
            CREATE TABLE real_time_consumptions (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, consumption numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_real_time_consumptions_period UNIQUE(date,time_of_period_id));
            CREATE TABLE primary_frequency_capacity_prices (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, price numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_primary_frequency_capacity_prices_period UNIQUE(date,time_of_period_id));
            CREATE TABLE secondary_frequency_capacity_prices (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, price numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_secondary_frequency_capacity_prices_period UNIQUE(date,time_of_period_id));
            CREATE TABLE system_directions (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, direction_id bigint NULL, direction varchar(100) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_system_directions_period UNIQUE(date,time_of_period_id));
            CREATE TABLE wind_generation_and_forecasts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, forecast numeric(18,6) NOT NULL, generation numeric(18,6) NOT NULL, quantile5 numeric(18,6) NOT NULL, quantile25 numeric(18,6) NOT NULL, quantile75 numeric(18,6) NOT NULL, quantile95 numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_wind_generation_and_forecasts_period UNIQUE(date,time_of_period_id));
            CREATE TABLE generation_plans (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, river numeric(18,6) NOT NULL, dam numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL, other numeric(18,6) NOT NULL, natural_gas numeric(18,6) NOT NULL, fuel_oil numeric(18,6) NOT NULL, solar numeric(18,6) NOT NULL, imported_coal numeric(18,6) NOT NULL, geothermal numeric(18,6) NOT NULL, lignite numeric(18,6) NOT NULL, naphtha numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL, hard_coal numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_generation_plans_period UNIQUE(date,time_of_period_id));
            CREATE TABLE first_version_generation_plans (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, river numeric(18,6) NOT NULL, dam numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL, other numeric(18,6) NOT NULL, natural_gas numeric(18,6) NOT NULL, fuel_oil numeric(18,6) NOT NULL, solar numeric(18,6) NOT NULL, imported_coal numeric(18,6) NOT NULL, geothermal numeric(18,6) NOT NULL, lignite numeric(18,6) NOT NULL, naphtha numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL, hard_coal numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_first_version_generation_plans_period UNIQUE(date,time_of_period_id));
            CREATE TABLE injection_quantities (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date date NOT NULL, time_of_period_id integer NOT NULL, asphaltite numeric(18,6) NOT NULL, biomass numeric(18,6) NOT NULL, dam numeric(18,6) NOT NULL, fuel_oil numeric(18,6) NOT NULL, geothermal numeric(18,6) NOT NULL, imported_coal numeric(18,6) NOT NULL, international_export numeric(18,6) NOT NULL, international_import numeric(18,6) NOT NULL, lignite numeric(18,6) NOT NULL, lng numeric(18,6) NOT NULL, naphtha numeric(18,6) NOT NULL, natural_gas numeric(18,6) NOT NULL, other numeric(18,6) NOT NULL, river numeric(18,6) NOT NULL, hard_coal numeric(18,6) NOT NULL, solar numeric(18,6) NOT NULL, wind numeric(18,6) NOT NULL, total numeric(18,6) NOT NULL, created_date timestamptz NOT NULL, updated_date timestamptz NULL, CONSTRAINT uq_injection_quantities_period UNIQUE(date,time_of_period_id));

            INSERT INTO integration_jobs (id,name,code,description,cron_expression,time_zone,queue_name,is_active,created_date) VALUES
              (3,'Yük Tahmin Planı','TRANSPARENCY_LOAD_ESTIMATION_PLAN','Bir sonraki günün saatlik yük tahmin planını getirir.','5 14 * * *','Europe/Istanbul','transparency',true,now()),
              (4,'RES Üretim ve Tahmin','TRANSPARENCY_RES_GENERATION_FORECAST','RES üretim ve tahmin verilerini getirir.','*/10 * * * *','Europe/Istanbul','transparency',true,now()),
              (5,'SFK Kapasite Fiyatı','TRANSPARENCY_SFK_PRICE','Saatlik SFK kapasite fiyatlarını getirir.','20 * * * *','Europe/Istanbul','transparency',true,now()),
              (6,'PFK Kapasite Fiyatı','TRANSPARENCY_PFK_PRICE','Saatlik PFK kapasite fiyatlarını getirir.','15 * * * *','Europe/Istanbul','transparency',true,now()),
              (7,'Uzlaştırma Esas Veriş Miktarı','TRANSPARENCY_UEVM','Saatlik UEVM verilerini getirir.','30 2 * * *','Europe/Istanbul','transparency',true,now()),
              (8,'Sistem Yönü','TRANSPARENCY_SYSTEM_DIRECTION','Saatlik sistem yönü verilerini getirir.','10 * * * *','Europe/Istanbul','transparency',true,now()),
              (9,'KGÜP İlk Versiyon','TRANSPARENCY_KGUP_FIRST_VERSION','KGÜP ilk versiyon verilerini getirir.','20 16 * * *','Europe/Istanbul','transparency',true,now()),
              (10,'KGÜP','TRANSPARENCY_KGUP','Kesinleşmiş günlük üretim planını getirir.','15 16 * * *','Europe/Istanbul','transparency',true,now()),
              (11,'Gerçek Zamanlı Tüketim','TRANSPARENCY_REALTIME_CONSUMPTION','Saatlik gerçek zamanlı tüketim verilerini getirir.','15 * * * *','Europe/Istanbul','transparency',true,now())
            ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, cron_expression=EXCLUDED.cron_expression, is_active=true;
            SELECT setval(pg_get_serial_sequence('integration_jobs','id'), (SELECT MAX(id) FROM integration_jobs));
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DELETE FROM integration_jobs WHERE code IN ('TRANSPARENCY_LOAD_ESTIMATION_PLAN','TRANSPARENCY_RES_GENERATION_FORECAST','TRANSPARENCY_SFK_PRICE','TRANSPARENCY_PFK_PRICE','TRANSPARENCY_UEVM','TRANSPARENCY_SYSTEM_DIRECTION','TRANSPARENCY_KGUP_FIRST_VERSION','TRANSPARENCY_KGUP','TRANSPARENCY_REALTIME_CONSUMPTION');
            DROP TABLE injection_quantities;
            DROP TABLE first_version_generation_plans;
            DROP TABLE generation_plans;
            DROP TABLE wind_generation_and_forecasts;
            DROP TABLE system_directions;
            DROP TABLE secondary_frequency_capacity_prices;
            DROP TABLE primary_frequency_capacity_prices;
            DROP TABLE real_time_consumptions;
            DROP TABLE load_estimation_plans;
            """);
    }
}
