using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyTrading.Infrastructure.Migrations;

[DbContext(typeof(EnergyTradingDbContext))]
[Migration("202608190003_RecreateWindGenerationForecastsWithQuarter")]
public partial class RecreateWindGenerationForecastsWithQuarter : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS wind_generation_and_forecasts;

            CREATE TABLE wind_generation_and_forecasts (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date date NOT NULL,
              time_of_period_id integer NOT NULL,
              quarter integer NOT NULL,
              hour time without time zone NOT NULL,
              forecast numeric(18,6) NOT NULL,
              generation numeric(18,6) NULL,
              quantile5 numeric(18,6) NOT NULL,
              quantile25 numeric(18,6) NOT NULL,
              quantile75 numeric(18,6) NOT NULL,
              quantile95 numeric(18,6) NOT NULL,
              created_date timestamptz NOT NULL,
              updated_date timestamptz NULL,
              CONSTRAINT ck_wind_generation_and_forecasts_period CHECK (time_of_period_id BETWEEN 1 AND 24),
              CONSTRAINT ck_wind_generation_and_forecasts_quarter CHECK (quarter BETWEEN 1 AND 4),
              CONSTRAINT uq_wind_generation_and_forecasts_period_quarter UNIQUE (date, time_of_period_id, quarter)
            );
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS wind_generation_and_forecasts;

            CREATE TABLE wind_generation_and_forecasts (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date date NOT NULL,
              time_of_period_id integer NOT NULL,
              forecast numeric(18,6) NOT NULL,
              generation numeric(18,6) NULL,
              quantile5 numeric(18,6) NOT NULL,
              quantile25 numeric(18,6) NOT NULL,
              quantile75 numeric(18,6) NOT NULL,
              quantile95 numeric(18,6) NOT NULL,
              created_date timestamptz NOT NULL,
              updated_date timestamptz NULL,
              CONSTRAINT uq_wind_generation_and_forecasts_period UNIQUE (date, time_of_period_id)
            );
            """);
    }
}
