-- Run as a PostgreSQL administrator. CREATE DATABASE cannot run inside a transaction.
SELECT 'CREATE DATABASE "EnergyTrading"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'EnergyTrading')\gexec

\connect "EnergyTrading"

CREATE TABLE IF NOT EXISTS integration_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  code varchar(100) NOT NULL UNIQUE,
  description varchar(1000),
  cron_expression varchar(100) NOT NULL,
  time_zone varchar(100) NOT NULL,
  queue_name varchar(50) NOT NULL,
  is_active boolean NOT NULL,
  created_date timestamptz NOT NULL,
  updated_date timestamptz NULL
);

CREATE TABLE IF NOT EXISTS integration_job_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_job_id bigint NOT NULL REFERENCES integration_jobs(id) ON DELETE RESTRICT,
  hangfire_job_id varchar(100),
  correlation_id uuid NOT NULL,
  response_code integer,
  status varchar(30) NOT NULL,
  is_success boolean NOT NULL,
  retry_count integer NOT NULL,
  error_description varchar(4000),
  started_date timestamptz NOT NULL,
  completed_date timestamptz,
  duration_milliseconds bigint,
  fetched_record_count integer NOT NULL,
  inserted_record_count integer NOT NULL,
  updated_record_count integer NOT NULL,
  created_date timestamptz NOT NULL,
  updated_date timestamptz
);

CREATE INDEX IF NOT EXISTS ix_integration_job_logs_correlation_id
  ON integration_job_logs(correlation_id);
CREATE INDEX IF NOT EXISTS ix_integration_job_logs_integration_job_id_started_date
  ON integration_job_logs(integration_job_id, started_date);

CREATE TABLE IF NOT EXISTS market_clearing_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  time_of_period_id integer NOT NULL,
  price numeric(18,6) NOT NULL,
  price_usd numeric(18,6) NOT NULL,
  price_eur numeric(18,6) NOT NULL,
  created_date timestamptz NOT NULL,
  updated_date timestamptz,
  CONSTRAINT uq_market_clearing_prices_date_period UNIQUE (date, time_of_period_id)
);

CREATE TABLE IF NOT EXISTS system_marginal_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  time_of_period_id integer NOT NULL,
  price numeric(18,6) NOT NULL,
  created_date timestamptz NOT NULL,
  updated_date timestamptz,
  CONSTRAINT uq_system_marginal_prices_date_period UNIQUE (date, time_of_period_id)
);

UPDATE integration_jobs SET code = 'TRANSPARENCY_PTF' WHERE code IN ('EPİAŞ_PTF', 'SEFFAFLIK_PTF');
UPDATE integration_jobs SET code = 'TRANSPARENCY_SMF' WHERE code IN ('EPIAS_SMF', 'SEFFAFLIK_SMF');

INSERT INTO integration_jobs
  (name, code, description, cron_expression, time_zone, queue_name, is_active, created_date)
VALUES
  ('EPİAŞ Market Clearing Price', 'TRANSPARENCY_PTF', 'Fetches daily PTF values from EPİAŞ.', '0 15 * * *', 'Europe/Istanbul', 'transparency', true, now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO integration_jobs
  (name, code, description, cron_expression, time_zone, queue_name, is_active, created_date)
VALUES
  ('EPİAŞ System Marginal Price', 'TRANSPARENCY_SMF', 'Fetches current-day system marginal prices from EPİAŞ.', '5 * * * *', 'Europe/Istanbul', 'transparency', true, now())
ON CONFLICT (code) DO UPDATE SET cron_expression = EXCLUDED.cron_expression;
